### ISSUE TITLE
Problem in core/metrics.py file

### ISSUE THREAD

**Issue by ahmadthecoder** [THUDM/KOBE#44]
Traceback (most recent call last):
  File "KOBE/core/train.py", line 365, in <module>
    train_model(model, data, optim, i, params, config, device, writer)
  File "KOBE/core/train.py", line 188, in train_model
    score = eval_model(model, data, params, config, device, writer)
  File "KOBE/core/train.py", line 297, in eval_model
    reference, candidate, params["log_path"], print, config
  File "/content/KOBE/core/utils/metrics.py", line 81, in bleu
    return float(result.split()[2][:-1])
IndexError: list index out of range

**Comment by qibinc** [comment]
Hi @ahmadthecoder ,

Thanks for your interest in this work! This error seems to be caused by empty result files. Could you check the txt files called `candidates.txt` and `reference.txt` under `experiments/<exp_name>/`?

**Comment by ahmadthecoder** [comment]
Hello, @qibinc I have resolved this problem. I was trying to give it path directly like

**Comment by qibinc** [comment]
Hi @ahmadthecoder , you are absolutely right. Thanks for the good advice! I apologize for the inconvenience. Meanwhile, I'm recently working on a refactored version of this code, which makes everything much cleaner and the visualization better and should come out before the end of the year. Please stay tuned! (You can check the progress at https://github.com/THUDM/KOBE/tree/dev)

**Comment by ahmadthecoder** [comment]
Thank you so much! I have thoroughly read the research paper and it is quite amazing. I would definitely participate in the future for its further improvements.

**Comment by qibinc** [comment]
Hi @ahmadthecoder ,

We have rewritten this codebase and significantly improved the installation, code quality, reproducibility and visualization. Here is a screenshot of the KOBE-v2's training progress, in case your are still interested:

![image](https://user-images.githubusercontent.com/22570685/147371146-f7d3ee8f-d62c-46e0-91fa-6b86dad56833.png)

Best,
